version: '3.9'
services:
  report_bot:
    build:
      context: report_bot
    container_name: report
    stop_signal: SIGKILL
    ports:
      - 5003:5003
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ./report_bot:/telegram_bot
    environment:
      - LOCAL_ENV=local
    develop:
      watch:
        - action: sync
          path: ./report_bot
          target: /telegram_bot
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  guide_guru:
    build:
      context: GuideGuru
    container_name: guide_guru
    stop_signal: SIGKILL
    ports:
      - 5002:5002
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ./GuideGuru:/telegram_bot
    environment:
      - LOCAL_ENV=local
    develop:
      watch:
        - action: sync
          path: ./GuideGuru
          target: /telegram_bot
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
