version: '3.9'
services:
  report_bot:
    build:
      context: report_bot
    stop_signal: SIGKILL
    ports:
      - 5003:5003
    networks:
      - webnet
    depends_on:
      - postgres

  guide_guru:
    build:
      context: GuideGuru
    stop_signal: SIGKILL
    ports:
      - 5002:5002
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet: